name: Deploy Supabase

on:
  push:
    branches: [main]

jobs:
  supabase:
    runs-on: ubuntu-20.04
    env:
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
      SUPABASE_DB_PASSWORD: ${{ secrets.SUPABASE_DB_PASSWORD }}
      PROJECT_ID: ${{ vars.SUPABASE_PROJECT_ID }}

    steps:
      - uses: supabase/setup-cli@v1
      - run: supabase link --project-ref $PROJECT_ID
      - run: supabase db push
